name: pium
description: PIUM - AI-assisted accessible launcher for active seniors.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.1.0
  geocoding: ^4.0.0
  geolocator: ^13.0.2
  supabase_flutter: ^2.8.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/data/sample_senior_jobs_response.json
    - lib/data/korean_regions.json
